In [2]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import chi2_contingency
import seaborn as sns
from random import randrange, uniform

In [3]:
os.chdir("C:/Users/Neelam/Desktop/Workradhika/project")

In [4]:
#reading the excell file
df = pd.read_excel("churndata.xlsx")

In [8]:
df1.dtypes

account_length                     int64
international_plan                object
voice_mail_plan                   object
number_vmail_messages              int64
total_day_minutes                float64
total_day_calls                    int64
total_day_charge                 float64
total_eve_minutes                float64
total_eve_calls                    int64
total_eve_charge                 float64
total_night_minutes              float64
total_night_calls                  int64
total_night_charge               float64
total_intl_minutes               float64
total_intl_calls                   int64
total_intl_charge                float64
number_customer_service_calls      int64
churn                             object
dtype: object

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ','_').str.replace('(' , ' ').str.replace(')', '')

In [7]:
df1 = df.drop(['state','area_code', 'phone_number'] , axis = 1)

In [9]:
#Create dataframe with missing percentage
missing_val = pd.DataFrame(df1.isnull().sum())

#Reset index
missing_val = missing_val.reset_index()

#Rename variable
missing_val = missing_val.rename(columns = {'index': 'Variables', 0: 'Missing_percentage'})

#Calculate percentage
missing_val['Missing_percentage'] = (missing_val['Missing_percentage']/len(df1))*100

#descending order
missing_val = missing_val.sort_values('Missing_percentage', ascending = False).reset_index(drop = True)

#save output results 
missing_val.to_csv("Miising_perc.xlsx", index = False)

In [10]:
#replace -1 with NA to impute
for i in range(0, df1.shape[1]):
    df1.iloc[:,i] = df1.iloc[:,i].replace(-1, np.nan)

In [11]:
#Assigning levels to the categories
lis = []
for i in range(0, df1.shape[1]):
    if(df1.iloc[:,i].dtypes == 'object'):
        df1.iloc[:,i] = pd.Categorical(df1.iloc[:,i])
        df1.iloc[:,i] = df1.iloc[:,i].cat.codes 
        df1.iloc[:,i] = df1.iloc[:,i].astype('object')
        
        lis.append(df1.columns[i])

In [22]:
lis

['voice_mail_plan', 'churn']

In [25]:
df1.dtypes

account_length                      int64
international_plan               category
voice_mail_plan                    object
number_vmail_messages               int64
total_day_minutes                 float64
total_day_calls                     int64
total_day_charge                  float64
total_eve_minutes                 float64
total_eve_calls                     int64
total_eve_charge                  float64
total_night_minutes               float64
total_night_calls                   int64
total_night_charge                float64
total_intl_minutes                float64
total_intl_calls                    int64
total_intl_charge                 float64
number_customer_service_calls       int64
churn                              object
dtype: object

In [15]:
df1.head()

,account_length,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,128,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,False
1,107,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,False
2,137,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,False
3,84,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,False
4,75,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,False

In [128]:
#replace target categories with Yes or No
df1['churn'] = df1['churn'].replace(0, 'False')
df1['churn'] = df1['churn'].replace(1, 'True')

In [129]:
df1.head()

,account_length,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,128,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,True
1,107,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,True
2,137,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,True
3,84,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,True
4,75,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,True

In [130]:
#Divide data into train and test
X = df1.values[:, 0:17]
Y = df1.values[:,17]

X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.2)

In [131]:
#Import Libraries for decision tree
from sklearn.cross_validation import train_test_split
from sklearn.preprocessing import StandardScaler

In [27]:
#Random Forest
from sklearn.ensemble import RandomForestClassifier

RF_model = RandomForestClassifier(n_estimators = 20).fit(X_train, y_train)

C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\sklearn\ensemble\weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d

In [28]:
RF_Predictions = RF_model.predict(X_test)

In [30]:
RF_model

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=20, n_jobs=1,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [33]:
RF_Predictions

array(['False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'True', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'False', 'True', 'False', 'False', 'False', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'True', 'True', 'False', 'False', 'True', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'True', 'False', 'False',
       'False', 'True', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'True', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'True', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'True', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'False', 'True', 'False', 'True', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'True', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'True', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'False', 'False', 'True', 'True', 'False',
       'False', 'False', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False', 'False',
       'False', 'True', 'False', 'False', 'False', 'True', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'True', 'False', 'True', 'False',
       'False', 'False', 'False', 'True', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'False', 'True', 'False', 'False', 'False', 'False',
       'False', 'False', 'False', 'False', 'True', 'False', 'False',
       'False', 'False', 'False', 'False', 'False', 'False', 'True',
       'False', 'False', 'False', 'False', 'False', 'False'], dtype=object)

In [98]:
#build confusion matrix
# from sklearn.metrics import confusion_matrix 
# CM = confusion_matrix(y_test, y_pred)
CM = pd.crosstab(y_test, RF_Predictions)

#let us save TP, TN, FP, FN
TN = CM.iloc[0,0]
FN = CM.iloc[1,0]
TP = CM.iloc[1,1]
FP = CM.iloc[0,1]

#check accuracy of model
#accuracy_score(y_test, y_pred)*100
((TP+TN)*100)/(TP+TN+FP+FN)

#False Negative rate 
#(FN*100)/(FN+TP)

#Accuracy: 95.8
#FNR: 29.10

95.8

In [99]:
#False Negative rate 
(FN*100)/(FN+TP)

29.104477611940297

In [142]:
#Let us prepare data for logistic regression
#replace target categories with FALSE and TRUE
df1['churn'] = df1['churn'].replace('True', 1)
df1['churn'] = df1['churn'].replace('False', 0)

In [143]:
df1.head()

,account_length,international_plan,voice_mail_plan,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls,churn
0,128,0,1,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1,1
1,107,0,1,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1,1
2,137,0,0,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0,1
3,84,1,0,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2,1
4,75,1,0,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3,1

In [144]:
#Create logistic data. Save target variable first
df1_logit = pd.DataFrame(df1['churn'])

In [145]:
cnames = ["account_length" , "number_vmail_messages" ,"total_day_minutes" , "total_day_calls" , "total_day_charge" ,"total_eve_minutes" ,"total_eve_calls" , "total_eve_charge" , "total_night_minutes" ,"total_night_calls" , "total_night_charge" , "total_intl_minutes" , "total_intl_calls" , "total_intl_charge" ,"number_customer_service_calls"]

In [146]:
#Add continous variables
df1_logit = df1_logit.join(df1[cnames])

In [147]:
df1_logit.head()

,churn,account_length,number_vmail_messages,total_day_minutes,total_day_calls,total_day_charge,total_eve_minutes,total_eve_calls,total_eve_charge,total_night_minutes,total_night_calls,total_night_charge,total_intl_minutes,total_intl_calls,total_intl_charge,number_customer_service_calls
0,1,128,25,265.1,110,45.07,197.4,99,16.78,244.7,91,11.01,10.0,3,2.70,1
1,1,107,26,161.6,123,27.47,195.5,103,16.62,254.4,103,11.45,13.7,3,3.70,1
2,1,137,0,243.4,114,41.38,121.2,110,10.30,162.6,104,7.32,12.2,5,3.29,0
3,1,84,0,299.4,71,50.90,61.9,88,5.26,196.9,89,8.86,6.6,7,1.78,2
4,1,75,0,166.7,113,28.34,148.3,122,12.61,186.9,121,8.41,10.1,3,2.73,3

In [148]:
##Create dummies for categorical variables
cat_names = ["international_plan", "voice_mail_plan"]

for i in cat_names:
    temp = pd.get_dummies(df1[i], prefix = i)
    df1_logit = df1_logit.join(temp)

In [149]:
Sample_Index = np.random.rand(len(df1_logit)) < 0.8

train = df1_logit[Sample_Index]
test = df1_logit[~Sample_Index]

In [150]:
#select column indexes for independent variables
train_cols = train.columns[1:30]

In [90]:
#Built Logistic Regression
import statsmodels.api as sm

logit = sm.Logit(train['churn'], train[train_cols]).fit()

logit.summary()

Optimization terminated successfully.
         Current function value: 0.315918
         Iterations 10

C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\statsmodels\base\model.py:1092: RuntimeWarning: invalid value encountered in sqrt
  bse_ = np.sqrt(np.diag(self.cov_params()))
C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in greater
  return (self.a < x) & (x < self.b)
C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\scipy\stats\_distn_infrastructure.py:879: RuntimeWarning: invalid value encountered in less
  return (self.a < x) & (x < self.b)
C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\scipy\stats\_distn_infrastructure.py:1821: RuntimeWarning: invalid value encountered in less_equal
  cond2 = cond0 & (x <= self.a)

<class 'statsmodels.iolib.summary.Summary'>
"""
                           Logit Regression Results
==============================================================================
Dep. Variable:                  churn   No. Observations:                 4020
Model:                          Logit   Df Residuals:                     4002
Method:                           MLE   Df Model:                           17
Date:                Sat, 01 Dec 2018   Pseudo R-squ.:                  0.2261
Time:                        19:22:16   Log-Likelihood:                -1270.0
converged:                       True   LL-Null:                       -1641.0
                                        LLR p-value:                1.042e-146
=================================================================================================
                                    coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------------------
account_length                   -0.0009      0.001     -0.667      0.505      -0.003       0.002
number_vmail_messages            -0.0430      0.017     -2.499      0.012      -0.077      -0.009
total_day_minutes                -4.9572      3.022     -1.640      0.101     -10.881       0.967
total_day_calls                  -0.0017      0.003     -0.681      0.496      -0.007       0.003
total_day_charge                 29.0753     17.779      1.635      0.102      -5.771      63.922
total_eve_minutes                -0.2177      1.516     -0.144      0.886      -3.189       2.753
total_eve_calls                   0.0026      0.003      0.984      0.325      -0.003       0.008
total_eve_charge                  2.4860     17.834      0.139      0.889     -32.467      37.439
total_night_minutes              -0.1282      0.812     -0.158      0.874      -1.719       1.462
total_night_calls                 0.0008      0.003      0.303      0.762      -0.004       0.006
total_night_charge                2.7602     18.033      0.153      0.878     -32.585      38.105
total_intl_minutes                3.5613      4.878      0.730      0.465      -6.000      13.123
total_intl_calls                  0.0656      0.022      2.921      0.003       0.022       0.110
total_intl_charge               -13.4983     18.068     -0.747      0.455     -48.912      21.915
number_customer_service_calls    -0.5181      0.037    -14.050      0.000      -0.590      -0.446
international_plan_0              5.2664        nan        nan        nan         nan         nan
international_plan_1              3.1277        nan        nan        nan         nan         nan
voice_mail_plan_0                 2.9670        nan        nan        nan         nan         nan
voice_mail_plan_1                 5.4272        nan        nan        nan         nan         nan
=================================================================================================
"""

In [151]:
#Predict test data
test['Actual_prob'] = logit.predict(test[train_cols])

test['ActualVal'] = 1
test.loc[test.Actual_prob < 0.5, 'ActualVal'] = 0

C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\Users\Neelam\Anaconda3\radhika\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s

In [158]:
#Build confusion matrix
CM = pd.crosstab(test['churn'], test['ActualVal'])

#let us save TP, TN, FP, FN
TN = CM.iloc[0,0]
FN = CM.iloc[1,0]
TP = CM.iloc[1,1]
FP = CM.iloc[0,1]

#check accuracy of model
 #accuracy_score(y_test, y_pred)*100
#((TP+TN)*100)/(TP+TN+FP+FN)

(FN*100)/(FN+TP)
#Accuracy: 85.85
#FNR: 3.419811

3.419811320754717

In [159]:
(FN*100)/(FN+TP)

3.419811320754717